Repository codestates-seb/PAWPAW, pull requests merged in 2023-03, with the labels that each got.

#159 Be/feat/pet
  server/src/main/java/animalsquad/server/domain/infomap/dto/InfoMapDetailsResponseDto.java
  server/src/main/java/animalsquad/server/domain/infomap/mapper/InfoMapMapper.java
  server/src/main/java/animalsquad/server/domain/pet/controller/PetController.java
  server/src/main/java/animalsquad/server/domain/pet/dto/PetResponseDto.java
  server/src/main/java/animalsquad/server/domain/pet/entity/Pet.java
  server/src/main/java/animalsquad/server/domain/pet/entity/PetStatus.java
  server/src/main/java/animalsquad/server/domain/pet/mapper/PetMapper.java
  server/src/main/java/animalsquad/server/domain/pet/service/PetService.java
  server/src/main/java/animalsquad/server/domain/post/dto/PostDetailsResponseDto.java
  server/src/main/java/animalsquad/server/domain/post/dto/PostsResponseDto.java
  server/src/main/java/animalsquad/server/domain/post/mapper/PostMapper.java
Labels: back

#155 [FE] fix: 기존 새로고침 방식 제거 config 변조를 통한 수정 방식 적용
  client/src/Pages/Domain.tsx
  client/src/util/GlobalAxios.tsx
Labels: front

#163 [BE] feat: 탈퇴 회원 로그인 시 예외 처리
  server/src/main/java/animalsquad/server/global/auth/handler/PetAuthenticationFailureHandler.java
  server/src/main/java/animalsquad/server/global/auth/userdetails/PetDetailsService.java
  server/src/main/java/animalsquad/server/global/exception/ExceptionCode.java
Labels: back

#164 [BE] 게시글 검색, 필터 기능
  server/build.gradle
  server/src/main/java/animalsquad/server/domain/post/controller/PostController.java
  server/src/main/java/animalsquad/server/domain/post/dto/PostSearchDto.java
  server/src/main/java/animalsquad/server/domain/post/repository/PostRepository.java
  server/src/main/java/animalsquad/server/domain/post/repository/PostRepositoryCustom.java
  server/src/main/java/animalsquad/server/domain/post/repository/PostRepositoryImpl.java
  server/src/main/java/animalsquad/server/domain/post/service/PostService.java
  server/src/main/java/animalsquad/server/global/auth/jwt/JwtTokenProvider.java
  server/src/main/java/animalsquad/server/global/exception/ExceptionCode.java
  server/src/main/resources-dev/application.yml
Labels: back

#169 Community
  client/src/Components/CommunityPost.tsx
  client/src/Components/Review.tsx
  client/src/Pages/Community.tsx
  client/src/Pages/CommunityDetail.tsx
  client/src/Pages/Domain.tsx
  client/src/Pages/Mypage.tsx
  client/src/components/Header.tsx
Labels: front

#171 [BE] feat: 회원 정보 조회 응답에 댓글 수 추가
  server/src/main/java/animalsquad/server/domain/pet/controller/PetController.java
  server/src/main/java/animalsquad/server/domain/pet/dto/PetResponseDto.java
  server/src/main/java/animalsquad/server/domain/pet/mapper/PetMapper.java
  server/src/main/java/animalsquad/server/domain/pet/service/PetService.java
Labels: back

#170 feat: 커뮤니티 정렬 기능
  client/src/App.css
  client/src/Components/CommunityReview.tsx
  client/src/Components/ModalReview.tsx
  client/src/Components/ModalReviewWrite.tsx
  client/src/Components/MypagePost.tsx
  client/src/Components/Review.tsx
  client/src/Components/SearchBar.tsx
  client/src/Components/SortModal.tsx
  client/src/Pages/Community.tsx
  client/src/Pages/Mypage.tsx
  client/src/Pages/Profile.tsx
  client/src/Pages/UserInfoEdit.tsx
Labels: front

#172 [BE] feat: 게시글 페이지 상단 동네 친구들 추가
  server/src/main/java/animalsquad/server/domain/pet/repository/PetRepository.java
  server/src/main/java/animalsquad/server/domain/pet/service/PetService.java
  server/src/main/java/animalsquad/server/domain/post/controller/PostController.java
  server/src/main/java/animalsquad/server/domain/post/dto/PostsResponseDto.java
  server/src/main/java/animalsquad/server/domain/post/mapper/PostMapper.java
Labels: back

#175 [FE] fix : 자동 로그아웃 제거, refresh 중복 시 로그아웃 되도록 적용
  client/src/Pages/Domain.tsx
  client/src/Pages/Login.tsx
  client/src/util/GlobalAxios.tsx
  client/src/util/autoLogout.tsx
Labels: bug

#179 Refactoring
  README.md
  client/src/Map/Icons.tsx
  client/src/Map/Marker.tsx
  client/src/Map/Marker/CafeMarker.tsx
  client/src/Map/Marker/CampMarker.tsx
  client/src/Map/Marker/FoodMarker.tsx
  client/src/Map/Marker/HospitalMarker.tsx
  client/src/Map/Marker/MyMarker.tsx
  client/src/Map/Marker/ParkMarker.tsx
  client/src/Map/Marker/PoolMarker.tsx
Labels: front

#181 [FE] 지역별 정렬 기능 추가(지역별 친구 추천은 미포함)
  client/package.json
  client/src/Components/AreaSort.tsx
  client/src/Pages/Community.tsx
  client/src/Pages/Domain.tsx
Labels: front

#182 [FE] fix: merge 오류 수정
  client/src/Components/SortModal.tsx
  client/src/Pages/Community.tsx
  client/src/Pages/Domain.tsx
Labels: front

#176 [BE] feat: 회원 탈퇴 시 기본 이미지로 변경
  server/src/main/java/animalsquad/server/domain/pet/service/PetService.java
  server/src/main/java/animalsquad/server/global/exception/ExceptionCode.java
  server/src/main/java/animalsquad/server/global/s3/service/FileUploadService.java
Labels: back

#183 [FE] 친구 추천 기능
  client/src/Components/Friend.tsx
  client/src/Components/FriendRecommend.tsx
  client/src/Pages/Community.tsx
  client/src/types.ts
Labels: front

#186 [FE] 친구 추천버튼 클릭시 친구 페이지로 이동 및 CI/CD 설정
  .github/workflows/test-deploy-work.yml
  .github/workflows/testClient.yml
  client/public/index.html
  client/src/Components/Friend.tsx
  client/src/Components/FriendRecommend.tsx
  client/src/Components/Header.tsx
  client/src/Pages/Community.tsx
  client/src/Pages/Domain.tsx
  client/src/Pages/Friendpage.tsx
  client/src/types.ts
Labels: front

#187 [FE] 클라이언트 S3 깃허브 액션 배포 후 성공 유무 디스코드 알림 및 main 브렌치 배포 yml 설정
  .github/workflows/mainDeploy.yml
  .github/workflows/testClient.yml
Labels: front

#190 [FE] : Signup fix
  client/src/Pages/SignUp.tsx
  client/src/Pages/UserInfo.tsx
Labels: bug
